# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-13 07:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vip', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vip',
            options={'ordering': ['level']},
        ),
        migrations.AlterField(
            model_name='permission',
            name='name',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
